services:
  mysqldb:
    image: mysql:8.0
    restart: always
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db1
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h", "localhost","-u","root","-pabiskar"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    tty: true
    